INVALID_JOB_STRUCTURE="invalid job structure"
INVALID_JOB_TYPE="invalid job type"
JOB_ADDED_SUCCESS="job successfully added"
JOB_UPDATED_SUCCESS="job updated successfully"
JOB_DOESNOT_EXISTS="job doesnot exists"